version: "3"

services:
  app-ui:
    image: youtube-to-mp3-ui:0.0.1
    ports:
      - 80
    depends_on:
      - nginx-lb-back

  app-back:
    image: youtube-to-mp3-back:0.0.1
    ports:
      - 3000

  nginx-lb-ui:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-lb-ui.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/www.univnexus.com/fullchain.pem:/etc/fullchain.pem
      - /etc/letsencrypt/live/www.univnexus.com/privkey.pem:/etc/privkey.pem
    depends_on:
      - app-ui

  nginx-lb-back:
    image: nginx
    # ports:
    #   - 81:80
    volumes:
      - ./nginx-lb-back.conf:/etc/nginx/nginx.conf
    depends_on:
      - app-back
